{% set name = "osc-lib" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f706be145daf0e58068e3763ec56bde2f43ed229a738628e4c0fb1defb4ed9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python 3.8
    - setuptools
  run:
    - cliff >=3.2.0
    - keystoneauth1 >=3.14.0
    - openstacksdk >=0.15.0
    - oslo.i18n >=3.15.3
    - oslo.utils >=3.33.0
    - pbr
    - python 3.8
    - setuptools
    - stevedore >=1.20.0

test:
  imports:
    - osc_lib

about:
  home: https://opendev.org/openstack/osc-lib
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStackClient Library
  doc_url: https://docs.openstack.org/osc-lib/latest/
  dev_url: https://opendev.org/openstack/osc-lib

extra:
  recipe-maintainers:
    - tschoonj
